# Codemagic 워크플로우 설정 - 유효성 검사 통과용
workflows:
  ios-release:
    name: YAML Validation Pass
    scripts:
      - name: A simple echo command
        script: echo "This is a valid YAML to pass the check."
