# Codemagic 워크플로우 설정 - 최종 수정본
workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nanoset.LuckyTenCommandmentsFresh"
      groups:
        - supabase
        - appstore_credentials 

    scripts:
      - name: Clean Xcode signing settings
        script: | 
          xcode-project remove-code-signing
      - name: Set up .env file
        script: | 
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
      - name: Install dependencies
        script: | 
          flutter pub get
      - name: Build IPA with release mode
        script: | 
          flutter build ipa --release --build-name=1.0.0 --build-number=1

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER # 이 이름이 남아있는 변수와 일치합니다.
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
