# Codemagic 워크플로우 설정 - 최종 수정본
workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    
    integrations:
      app_store_connect: LuckyTenAPI

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - supabase 

    scripts:
      - name: Force remove Xcode code signing settings
        script: | 
          # Xcode 프로젝트 파일을 직접 찾아 서명 관련 설정을 강제로 제거합니다.
          PROJECT_FILE=$(find ios -name "project.pbxproj")
          sed -i.bak 's/ProvisioningStyle = Manual;/ProvisioningStyle = Automatic;/g' $PROJECT_FILE
          sed -i.bak 's/PROVISIONING_PROFILE_SPECIFIER = ".*";//g' $PROJECT_FILE
          sed -i.bak '/"CODE_SIGN_IDENTITY\[sdk=iphoneos\*\]"/d' $PROJECT_FILE
          echo "Force-removed Xcode signing settings."
      - name: Set up .env file
        script: | 
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
      - name: Install dependencies
        script: | 
          flutter pub get
      - name: Build IPA with release mode
        script: | 
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        submit_to_testflight: true
