# Codemagic 워크플로우 설정 - 최종 완성본
workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    
    # 1. API 키 연동
    integrations:
      app_store_connect: LuckyTenAPI

    # 2. 빌드 환경 (번들 ID 직접 지정)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # 이 부분이 GUI의 빈 칸 문제를 해결합니다.
        BUNDLE_ID: "com.nanoset.LuckyTenCommandmentsFresh"
      groups:
        - supabase 

    # 3. 빌드 스크립트
    scripts:
      - name: Clean Xcode signing settings
        script: | 
          # Xcode 프로젝트의 기존 서명 설정을 제거하여 충돌을 방지합니다.
          xcode-project remove-code-signing
      - name: Set up .env file
        script: | 
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
      - name: Install dependencies
        script: | 
          flutter pub get
      - name: Build IPA with release mode
        script: | 
          flutter build ipa --release --build-name=1.0.0 --build-number=1

    # 4. 빌드 결과물
    artifacts:
      - build/ios/ipa/*.ipa

    # 5. 서명 및 배포
    publishing:
      # 이 블록 하나로 서명과 업로드를 모두 처리합니다.
      app_store_connect:
        # 인증은 integrations에 있는 API 키를 자동으로 상속받아 사용합니다.
        submit_to_testflight: true
