# Codemagic 워크플로우 설정 - App Store 제출용 IPA 빌드
workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.nanoset.luckyTenCommandmentsFresh"
        APP_STORE_APP_ID: "<App Store App ID (선택)>"
        TEAM_ID: "NCB9774DGY"
      groups:
        - supabase
        - app_store_connect_integration
    integrations:
      app_store_connect: codemagic
    triggering:
      events:
        - push
    scripts:
      - name: 📦 Install dependencies
        script: |
          flutter pub get
      - name: 🧹 Clean
        script: |
          flutter clean
      - name: 🔨 Build IPA
        script: |
          flutter build ipa --release --export-options-plist=ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
