# Codemagic 워크플로우 설정 - 최종 수정본
workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    
    # API 키 연동 (이 부분은 올바르게 설정되어 있었습니다)
    integrations:
      app_store_connect: LuckyTenAPI

    # 빌드 환경
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - supabase 

    # 빌드 스크립트
    scripts:
      - name: Clean Xcode signing settings
        script: | 
          xcode-project remove-code-signing
      - name: Set up .env file
        script: | 
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
      - name: Install dependencies
        script: | 
          flutter pub get
      - name: Build IPA with release mode
        script: | 
          flutter build ipa --release

    # 빌드 결과물
    artifacts:
      - build/ios/ipa/*.ipa

    # --- 이 아랫부분이 오류를 해결한 최종 publishing 섹션입니다 ---
    publishing:
      # 이 블록 하나로 서명과 업로드를 모두 처리합니다.
      app_store_connect:
        # 1. 인증 정보: integrations에 있는 API 키를 사용하라고 명시합니다.
        api_key_integration_name: LuckyTenAPI

        # 2. TestFlight 업로드 설정
        submit_to_testflight: true
