workflows:
  ios-release:
    name: iOS Build Test
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: | 
          flutter pub get
      - name: Run build command
        script: | 
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
